import React from "react"
import { Link } from "gatsby"

import "../styles/bootstrap.min.css"
// import "../styles/brands.min.css"
import "../styles/light.min.css"
// import "../styles/regular.min.css"
import "../styles/solid.min.css"
// import "../styles/duotone.min.css"
import "../styles/fontawesome.min.css"
import "../styles/custom-styles.css"


export default function Layout({ children }) {
  return (
    <>
<div>
  <div className="container-main" id="page">
    {/* Header */}
    <header className="header-main">
      <div className="container">
        <div className="brand"><a href="index.html" title="99 Generations"><img src="static/img/brand-99-generations.svg" alt="brand-99-generations" /></a></div>
        <div className="main-menu">
          <div className="menu-btn menu-bar"><div className="icon-bar"><span /></div></div>
          <div className="nav-bar">
            <div className="nav-inn">
              <div className="menu-close menu-bar"><button className="fal fa-times" /></div>
              <nav>
                <ul>
                  <li><a href="#">Pricing</a></li>
                  <li><a href="#">My Creations</a></li>
                  <li><a href="#">My Store</a></li>
                </ul>
              </nav>
              <div className="btn-out">
                <a href="#" className="btn btn-gray">CREDITS: <span className="count">30</span></a>
                {/* <a href="#" className=""><em className="fa fa-user" /></a> */}
                <a href="#" className="icon-user"><em className="fa fa-user" /></a>

                <a href="#" className="btn btn-blue">Sign up</a>			</div>
            </div>	
          </div>	
        </div>
        <div className="user-mbl"><a href="#" className="fa fa-user" /></div>
        <div className="overlay" />	
      </div>
    </header>
    {/* Content - Main */}
    <main className="content-main">
      <div className="split-cont">
        <div className="container">
          <h2>Create art</h2>
          <div className="feature-links">
            <div className="aside">
              <ul>
                <li className="active"><a href="#">Default</a></li>
                <li><a href="#">Advanced</a></li>
              </ul>
              <div className="sml-txt">.81 credits /image</div>
            </div>
          </div>
          <div className="row">
            <div className="col-lg-6">
              <div className="box">
                <div className="box-inn">
                  <form method="get" action="#">
                    <label>Enter a detailed description:</label>
                    <span style={{color: 'red', fontSize: 13}} id="error_create_art" />
                    <textarea name="commentsart2" id="commentsart2" cols={5} rows={5} placeholder="A digital painting of a puppy french poodle in space surrounded by 3d marshmallow unicorns and stars..." defaultValue={""} />
                  </form>
                </div>
                <p>Images generated by stable difussiion. Learn more.</p>
                <div className="btn-out"><button type="submit" name="btnart2" onclick="generateArtImage();" id="btnart2" className="btn">GENERATE ART</button></div>
              </div>
            </div>
            <div className="col-lg-6">
              <div className="feature-list">
                <div className="heading-top">
                  <div className="aside">
                    <h3>One click merchification &amp; e-Commerce</h3>
                    <p>Begin selling in minutes:</p>
                  </div>
                </div>
                <div className="article-wrap">
                  <div className="article-list">
                    <div className="article-out">
                      <div className="article">
                        <div className="box">
                          <div className="figure"><img src="static/img/photo-1.png" alt="photo-1" /></div>
                          <h3>1. Generate Art</h3>
                        </div>
                      </div>
                      <div className="article">
                        <div className="box">
                          <div className="figure"><img src="static/img/photo-2.png" alt="photo-2" /></div>
                          <h3>2. Make Merchandise</h3>
                        </div>
                      </div>
                      <div className="article">
                        <div className="box">
                          <div className="figure"><img src="static/img/photo-3.png" alt="photo-1" /></div>
                          <h3>3. Sell Merch Online</h3>
                        </div>
                      </div>
                      <div className="arrows">
                        <a href="#" className="arrow-right purple"><em className="fal fa-arrow-right" /></a>
                        <a href="#" className="arrow-right"><em className="fal fa-arrow-right" /></a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="split-cont2">
        <div className="container">		
          <div className="row">
            <div className="col-md-6">
              <div className="figure" id="imageDiffusion"><img id="testimg" src="static/img/photo-4.png" alt="photo-4" /></div>
            </div>
            <div className="col-md-6">
              <div className="feature-links">
                <h3>Popular categories</h3>
                <div className="aside-wrap">
                  <div className="aside">
                    <ul>
                      <li className="active"><a href="#">Doggies</a></li>
                      <li><a href="#">Space</a></li>
                      <li><a href="#">Cars</a></li>
                      <li><a href="#">Bubbles</a></li>
                      <li><a href="#">Diamonds</a></li>
                      <li><a href="#">Superhero’s</a></li>
                      <li><a href="#">Category</a></li>
                      <li><a href="#">Fashion</a></li>
                      <li><a href="#">Funny</a></li>
                      <li><a href="#">Games</a></li>
                      <li><a href="#">Category</a></li>
                      <li><a href="#">Category</a></li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>		
        </div>
      </div>
      <div className="introducing-cont">
        <div className="container">
          <div className="row">
            <div className="col-md-6">
              <div className="heading-txt">
                <div className="sub-title">Introducing</div>
                <div className="sub-head">Remixer</div>
                <h2>Edit existing<br /> images</h2>
                <p>Over 5,000,000 amazing images available through Lexica art.</p>
                <div className="btn-out"><a href="#" className="btn">sign up</a></div>
              </div>
            </div>
            <div className="col-md-6">
              <div className="figure"><img src="static/img/introducing-group.png" alt="introducing-group" /></div>
            </div>
          </div>
        </div>
      </div>
      <div className="featured-images">
        <div className="container">
          <div className="heading-txt">
            <div className="sub-title">Featured images</div>
            <h2>Click to Remix</h2>
            <p>Start creating</p>
          </div>
          <div className="row">
            <div className="col-lg-4 col-sm-6">
              <div className="box">
                <div className="figure"><img src="static/img/featured-image-1.png" alt="featured-image-1" /> <div className="btns"><a href="#" className="btn btn-blue">REMIX <em className="icn-rex" /></a> <a href="#" className="btn btn-blue">MERCHIFY <em className="icn-crt" /></a></div></div>
                <h3>3D</h3>
              </div>
            </div>
            <div className="col-lg-4 col-sm-6">
              <div className="box">
                <div className="figure"><img src="static/img/featured-image-2.png" alt="featured-image-2" /> <div className="btns"><a href="#" className="btn btn-blue">REMIX <em className="icn-rex" /></a> <a href="#" className="btn btn-blue">MERCHIFY <em className="icn-crt" /></a></div></div>
                <h3>Abstract</h3>
              </div>
            </div>
            <div className="col-lg-4 col-sm-6">
              <div className="box">
                <div className="figure"><img src="static/img/featured-image-3.png" alt="featured-image-3" /> <div className="btns"><a href="#" className="btn btn-blue">REMIX <em className="icn-rex" /></a> <a href="#" className="btn btn-blue">MERCHIFY <em className="icn-crt" /></a></div></div>
                <h3>Architecture</h3>
              </div>
            </div>
            <div className="col-lg-4 col-sm-6">
              <div className="box">
                <div className="figure"><img src="static/img/featured-image-4.png" alt="featured-image-4" /> <div className="btns"><a href="#" className="btn btn-blue">REMIX <em className="icn-rex" /></a> <a href="#" className="btn btn-blue">MERCHIFY <em className="icn-crt" /></a></div></div>
                <h3>Nature</h3>
              </div>
            </div>
            <div className="col-lg-4 col-sm-6">
              <div className="box">
                <div className="figure"><img src="static/img/featured-image-5.png" alt="featured-image-5" /> <div className="btns"><a href="#" className="btn btn-blue">REMIX <em className="icn-rex" /></a> <a href="#" className="btn btn-blue">MERCHIFY <em className="icn-crt" /></a></div></div>
                <h3>Art &amp; Deco</h3>
              </div>
            </div>
            <div className="col-lg-4 col-sm-6">
              <div className="box">
                <div className="figure"><img src="static/img/featured-image-6.png" alt="featured-image-6" /> <div className="btns"><a href="#" className="btn btn-blue">REMIX <em className="icn-rex" /></a> <a href="#" className="btn btn-blue">MERCHIFY <em className="icn-crt" /></a></div></div>
                <h3>Textures</h3>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="generate-art-form">
        <div className="container">
          <div className="box">
            <form method="get" action="#">
              <label>What do you want to see?</label>
              <textarea name="commentsart" id="commentsart" cols={5} rows={5} placeholder="A digital painting of a puppy french poodle in space surrounded by 3d marshmallow unicorns and stars..." defaultValue={""} />
            </form>
            <p>Images generated by stable difussiion. Learn more.</p>
          </div>	
          <div className="btn-out"><button type="submit" name="btnart" id="btnart" className="btn radius-13">GENERATE ART</button></div>
        </div>
      </div>
    </main>
    {/* Footer */}
    <footer className="footer-main">
      <div className="container">
        <div className="newsletter-form-wrap">
          <div className="newsletter-form">
            <label>Begin creating</label>
            <form method="get" action="#">
              <input type="text" name="newsletter" id="newsletter" placeholder="Enter your email" />
              <input type="submit" name="newslettersubmit" id="newslettersubmit" className="btn btn-blue" defaultValue="Sign up" />
            </form>
          </div>
        </div>
        <div className="icons"><img src="static/img/icons-ai.svg" alt="icons-ai" /></div>
        <div className="brand"><a href="index.html" title="AtlasHoldings"><img src="static/img/brand-99generations.svg" alt="brand-99generations" /></a></div>
        <div className="foot-menu">
          <ul>
            <li><a href="#">Pricing</a></li>
            <li><a href="#">My Creations</a></li>
            <li><a href="#">My Store</a></li>
          </ul>
        </div>	
        <div className="foot-sub-title">By robots, for humans.™</div>
        <div className="foot-wrap">
          <p>©2022</p>
          <div className="foot-menu2">
            <ul>		
              <li><a href="terms.html">Terms &amp; Conditions</a></li>	
              <li><a href="privacy.html">Privacy</a></li>
              <li><a href="cookie-policy.html">Cookie Policy</a></li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
  </div>
</div>
    </>
  )
}